"""added nullables equal false to some

Revision ID: f6aaaec7145d
Revises: 2f5832f3ca6d
Create Date: 2026-04-26 17:25:45.348504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6aaaec7145d'
down_revision: Union[str, Sequence[str], None] = '2f5832f3ca6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    op.alter_column('workouts', 'workout_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workouts', 'workout_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workouts', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workouts', 'calories_burned',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts', 'calories_burned',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workouts', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workouts', 'workout_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workouts', 'workout_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
